services:
  # backend:
  #   build: ./backend
  #   container_name: internship-backend-RAG
  #   ports:
  #     - "${BACKEND_PORT}:8003"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_NAME=${POSTGRES_DB}
  #     - DB_USER=${POSTGRES_USER}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD}
  #     - DB_HOST=db
  #     - DB_PORT=${POSTGRES_PORT}
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - .env
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
  
  backend-web-service:
    build: ./backend-web
    container_name: internship-backend-web
    ports:
      - "${BACKEND_NODE_PORT}:3000"
    depends_on:
      - db
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${POSTGRES_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./backend-web:/app
    env_file:
      - .env
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: internship-frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  db:
    image: pgvector/pgvector:pg15
    container_name: internship-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: internship-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: